#[Info]
site_name: ç‹ç§‘æ–‡çš„ä¸ªäººç½‘ç«™
site_url: http://wcowin.work/
site_author: ç‹ç§‘æ–‡(Wcowin)
#[UI]
theme:
  name: material
  font:
    text: Bitter
  icon:
    logo: material/library-shelves
    admonition:
      <type>: material/file-alert-outline

  favicon: img/11.ico
  palette:
    #primary: blue grey
    
    - media: "(prefers-color-scheme: light)"
      scheme: default # æ—¥é—´æ¨¡å¼
      primary: blue grey # ä¸Šæ–¹çš„
      accent: cyan # é“¾æ¥ç­‰å¯äº¤äº’å…ƒä»¶çš„é«˜äº®è‰²
      toggle:
        icon: material/weather-night # å›¾æ ‡
        name: åˆ‡æ¢è‡³å¤œé—´æ¨¡å¼ # é¼ æ ‡æ‚¬æµ®æç¤º
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # å¤œé—´æ¨¡å¼
      primary: black 
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: åˆ‡æ¢è‡³æ—¥é—´æ¨¡å¼
  features: 
    - navigation.instant #- header.autohide  #è‡ªåŠ¨éšè—
    - announce.dismiss #å‘ˆç°å¯æ ‡è®°ä¸ºç”±ç”¨æˆ·è¯»å–çš„ä¸´æ—¶å…¬å‘Šï¼Œå¯ä»¥åŒ…å«ä¸€ä¸ªç”¨äºå–æ¶ˆå½“å‰å…¬å‘Šçš„æŒ‰é’®
    - navigation.tracking #åœ°å€æ ä¸­çš„ URL å°†è‡ªåŠ¨æ›´æ–°ä¸ºåœ¨ç›®å½•ä¸­çªå‡ºæ˜¾ç¤ºçš„æ´»åŠ¨é”šç‚¹
    - navigation.tabs #é¡¶çº§éƒ¨åˆ†å°†å‘ˆç°åœ¨ä¸Šé¢è§†å£æ ‡é¢˜ä¸‹æ–¹çš„èœå•å±‚ä¸­ï¼Œä½†åœ¨ç§»åŠ¨è®¾å¤‡ä¸Šä¿æŒåŸæ ·
    #- navigation.tabs.sticky  #å¯ç”¨ç²˜æ€§é€‰é¡¹å¡åï¼Œå¯¼èˆªé€‰é¡¹å¡å°†é”å®šåœ¨æ ‡é¢˜ä¸‹æ–¹ï¼Œå¹¶åœ¨å‘ä¸‹æ»šåŠ¨æ—¶å§‹ç»ˆä¿æŒå¯è§
    - navigation.sections #å¯ç”¨éƒ¨åˆ†åï¼Œé¡¶çº§éƒ¨åˆ†åœ¨è¾¹æ ä¸­å‘ˆç°ä¸º1220pxä»¥ä¸Šè§†å£çš„ç»„ï¼Œä½†åœ¨ç§»åŠ¨è®¾å¤‡ä¸Šä¿æŒåŸæ ·
    - navigation.top # è¿”å›é¡¶éƒ¨çš„æŒ‰é’® åœ¨ä¸Šæ»‘æ—¶å‡ºç°
    - search.suggest # æœç´¢è¾“å…¥ä¸€äº›å­—æ¯æ—¶æ¨èè¡¥å…¨æ•´ä¸ªå•è¯
    - search.highlight # æœç´¢å‡ºçš„æ–‡ç« å…³é”®è¯åŠ å…¥é«˜äº®
    - navigation.expand # æ‰“å¼€Tabæ—¶å·¦ä¾§ç›®å½•å…¨éƒ¨å±•å¼€
    - navigation.indexes #å¯ç”¨èŠ‚ç´¢å¼•é¡µåï¼Œå¯ä»¥å°†æ–‡æ¡£ç›´æ¥é™„åŠ åˆ°èŠ‚
    - search.share #æœç´¢åˆ†äº«æŒ‰é’®
    - content.tabs.link
  language: zh # ä¸€äº›æç¤ºæ€§çš„æ–‡å­—ä¼šå˜æˆä¸­æ–‡
  

  icon: 
    repo: fontawesome/brands/github #å³ä¸Šè§’å›¾æ ‡
edit_uri: edit/main/docs # ç¼–è¾‘æŒ‰é’®è·³è½¬çš„é“¾æ¥ 
repo_url: https://github.com/Wcowin/Wcowin.github.io # å³ä¸Šè§’ç‚¹å‡»è·³è½¬çš„é“¾æ¥
repo_name: Wcowin.github.io # å³ä¸Šè§’çš„åå­—

# [Navigtion]
nav:
  - ä¸»é¡µ: index.md
  - åšå®¢:
    - å¥½ç”¨/å¥½ç©ç½‘ç«™åˆ†äº«: blog/Webplay.md
    - Mac/windowsè½¯ä»¶ç½‘ç«™æ±‡æ€»: blog/macsoft.md
    - Telegram ç¾¤ç»„ã€é¢‘é“ã€æœºå™¨äºº  æ±‡æ€»åˆ†äº«: blog/TG.md
    
    - æŠ€æœ¯åˆ†äº«:
        - Win11é•œåƒä¸‹è½½ã€å£çº¸åŠKMSæ¿€æ´» : blog/æŠ€æœ¯åˆ†äº«/win.md
        - è§£å†³è°·æ­Œç¿»è¯‘ç”¨ä¸äº†çš„é—®é¢˜: blog/æŠ€æœ¯åˆ†äº«/googletranslate.md
        - çˆ±å¿ƒä»£ç : blog/æŠ€æœ¯åˆ†äº«/aixin.md
        - ç§‘å­¦ä¸Šç½‘: blog/æŠ€æœ¯åˆ†äº«/kexue.md
    - MKdocs:
        - åˆ©ç”¨mkdocséƒ¨ç½²é™æ€ç½‘é¡µè‡³GitHub pages: blog/Mkdocs/mkdocs1.md
        - Mkdocséƒ¨ç½²é™æ€ç½‘é¡µè‡³GitHub pagesé…ç½®è¯´æ˜(mkdocs.yml): blog/Mkdocs/mkdocs2.md
        - è§£å†³ mkdocséƒ¨ç½² Github Pages è‡ªå®šä¹‰åŸŸåå¤±æ•ˆçš„é—®é¢˜: blog/Mkdocs/mkdocs3.md
    - Mac:
        - PDè™šæ‹Ÿæœº: blog/Mac/Pd.md
        - Macbookå¯åŠ¨å°é¡½å›ºåº”ç”¨å›¾æ ‡åˆ é™¤æ–¹æ³•: blog/Mac/shanchu.md
        - Homebrewå›½å†…å¦‚ä½•è‡ªåŠ¨å®‰è£…(å›½å†…åœ°å€)(Mac & Linux): blog/Mac/homebrew.md
        - Macçš„escé”®å¤±æ•ˆçš„è§£å†³æ–¹æ³•: blog/Mac/Macesc.md
        - Macå°æŠ€å·§:å»é™¤ç³»ç»Ÿæˆªå›¾åçš„æ—¥æœŸåç¼€: blog/Mac/jietu.md
        - å°å°MacæŠ€å·§: blog/Mac/xjiq.md
        - Macéšè—å½©è›‹: blog/Mac/maccd.md
        - Mac é”®ç›˜å¿«æ·é”®: blog/Mac/kjj.md
    - WIN:
        - å½»åº•å¸è½½360å®‰å…¨å«å£«çš„æ–¹æ³•: blog/Win/360.md
        - ä¸‰æ­¥å¸è½½ Microsoft Edge: blog/Win/edgexz.md
        - windowså¿«æ·é”®: blog/Win/winkjj.md
        - å®‰å“çš„å­ç³»ç»Ÿ: blog/Win/anzhuodezixit.md
    - å­¦æœ¯:
        - LaTeXå¸¸ç”¨ç¬¦å·æ•´ç†: blog/å­¦æœ¯/LaTeX.md
    - Python:
        - å°†Pythonæ–‡ä»¶.pyæ‰“åŒ…æˆ.exeå¯æ‰§è¡Œç¨‹åº: blog/py/python.md
        - pip: blog/py/pip.md
    - Cè¯­è¨€: 
        - Cç¬”è®°: blog/Cè¯­è¨€/c.md
    
  - å¼€å‘: 
    - Markdown: 
        - MarkdownæŒ‡å—: develop/Markdown/markdown.md
        - MWeb Pro: develop/Markdown/MWeb.md
    - What is Github: develop/Github.md
    - å¤§å‚ä»¬çš„è‰¯å¿ƒè½¯ä»¶ï½: develop/fenxiang.md
    - å†™ç»™æ‰€æœ‰ Mac ç”¨æˆ·çš„æ‘¸é±¼æŒ‡åŒ—: develop/Mac.md

  - é—²è¯:
    - å°ç±³: relax/xiaomo.md
    - Apple: relax/Apple.md
    - æ¨èçš„Books: relax/tuijianyuedu.md
    - å¦‚æ˜¯æˆ‘é—»: relax/rushiwowen.md
    - ç‹å†°å†°o(^â–½^)o: relax/wbb.md
    - è¯—æ–‡:
      - æ«æ¡¥å¤œæ³Š: relax/shiwen/fqyb.md
      - æ»•ç‹é˜åº: relax/shiwen/twgx.md
      - æœ›æ±Ÿå—Â·è¶…ç„¶å°ä½œ: relax/shiwen/sjcnh.md
      - å‡»é¼“: relax/shiwen/jg.md
      - é›¨éœ–é“ƒÂ·ç§‹åˆ«: relax/shiwen/yll.md
      - æ±ŸåŸå­Â·ä¹™å¯æ­£æœˆäºŒåæ—¥å¤œè®°æ¢¦: relax/shiwen/jcz.md
    - æ‚æ–‡:
        - ã€Šç›®é€ã€‹èŠ‚é€‰: relax/æ‚æ–‡/musong.md
        - å¤§å­¦ä¸€ä¸ªäººåƒé¥­å¾ˆä¸¢äººå—ï¼Ÿ: relax/æ‚æ–‡/dx.md
        - luv letter: relax/æ‚æ–‡/luv letter.md
        - æœ‰å“ªäº›ç»™ç”·å­©å­åœ¨è°ˆæ‹çˆ±æ—¶çš„å¿ å‘Šï¼Ÿ: relax/æ‚æ–‡/zhonggao.md
        - ğŸˆ: relax/æ‚æ–‡/cat.md
    - è§‚å½±:
        - æ¨èçš„ç•ªå‰§: relax/å½±è§†/tuijianfanju.md
        - æ¨èçš„ç”µå½±: relax/å½±è§†/tuijiandedianyin.md
        - æ¨èçš„ç”µè§†å‰§: relax/å½±è§†/tuijiandsj.md
    - éŸ³ä¹:
        - shape of you: relax/éŸ³ä¹/soy.md
        - Floating: relax/éŸ³ä¹/Floating.md
        - æœ±ç ‚: relax/éŸ³ä¹/zhusha.md
        - å…³äºéƒ‘å·çš„è®°å¿†: relax/éŸ³ä¹/gyzzdjy.md
        - è‹¥æŠŠä½ : relax/éŸ³ä¹/rbn.md
        - çµ¶é ‚è®ƒæ­Œ: relax/éŸ³ä¹/jdzg.md
    - Game:
        - åŸç¥: relax/Game/yuanshen.md
        - å¦‚ä½•ç©å¥½ã€Šç‹è€…è£è€€ã€‹ï¼Ÿ: relax/Game/wzry.md
    - å…¥å…šç»“ä¸šè€ƒè¯•é¢˜æ€»ç»“: relax/rudang.md
    
  - æ—…è¡Œ: 
    - é‡åº†: trip/CQ.md
    - Hometown: trip/LH.md
    
  - å…³äº:
    - ä¸ªäººå±¥å†: about/geren.md
    - ç½‘ç«™åˆ¶ä½œ: about/web.md
    - æ”¯æŒä½œè€…: about/zcw.md
    - Test: about/test.md
    - æ¯•ä¸šä¹‹å‰å€¼å¾—å»åšçš„30ä»¶äº‹: about/biye.md
  
  
copyright: Copyright &copy; 2022ç‹ç§‘æ–‡ # å·¦ä¸‹è§’çš„ç‰ˆæƒå£°æ˜
  

extra:
  generator: false  #åˆ é™¤é¡µè„šæ˜¾ç¤ºâ€œä½¿ç”¨ MkDocs ææ–™åˆ¶é€ â€
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/wcowin_
    - icon: fontawesome/brands/github
      link: https://github.com/Wcowin
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/1407028951?spm_id_from=333.1007.0.0
    - icon: fontawesome/solid/paper-plane
      link: mailto:<1135801806@qq.com> #è”ç³»æ–¹å¼

  analytics: 
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
  
  # consent:
  #   title: Cookie consent
  #   description: >- 
  #     æˆ‘ä»¬ä¹Ÿä½¿ç”¨cookiesæ¥è¯†åˆ«æ‚¨çš„é‡å¤è®¿é—®å’Œåå¥½æ¥è¡¡é‡æˆ‘ä»¬æ–‡æ¡£çš„æœ‰æ•ˆæ€§ä»¥åŠç”¨æˆ·æ˜¯å¦æ‰¾åˆ°ä»–ä»¬è¦æ‰¾çš„ä¸œè¥¿ã€‚
  #     å¦‚æœä½ åŒæ„,ä½ å¯ä»¥å¸®åŠ©æˆ‘ä»¬è®©æˆ‘ä»¬çš„ç½‘ç«™æ›´å¥½~ 
    #cookie 
      
plugins:
  # - glightbox:
  #     loop: true
  #     effect: zoom
  #     zoomable: true
  #     draggable: true
  #     height: auto
  - search:
      separator: '[\s\u200b\-]'
  - tags  #æ ‡ç­¾
  

markdown_extensions:
  - abbr
  - attr_list
  - admonition
  - def_list
  - footnotes
  - md_in_html
  - meta # æ”¯æŒMarkdownæ–‡ä»¶ä¸Šæ–¹è‡ªå®šä¹‰æ ‡é¢˜æ ‡ç­¾ç­‰
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences # ä»£ç å—é«˜äº®æ’ä»¶
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.arithmatex:  # latexæ”¯æŒ
      generic: true
  - toc:
      permalink: true # å›ºå®šæ ‡é¢˜ä½ç½®ä¸ºå½“å‰ä½ç½®
  - pymdownx.highlight: # ä»£ç å—é«˜äº®
      anchor_linenums: true
      linenums: true # æ˜¾ç¤ºè¡Œå·
      # auto_title: true # æ˜¾ç¤ºç¼–ç¨‹è¯­è¨€åç§°
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - markdown.extensions.toc:
      slugify: !!python/object/apply:pymdownx.slugs.slugify {kwds: {case: lower}}
      permalink: "\ue157"
  
     
extra_javascript:
  - javascripts/extra.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
  - stylesheets/exe.css

 
